#!/bin/bash

# official carbonapi does not support config file, all settings are set via command
# line args, which makes it hard to create fixed supervisor program:x block.
# This wrapper script parses a configuration file and start carbonapi correspondingly.

source "$1"
exec carbonapi \
    -z "${ZIPPER_URL:-http://127.0.0.1:8080}" \
    -p "${LISTEN_PORT:-5000}" \
    -graphite "${GRAPHITE_URL:-127.0.0.1:2003}" \
    -prefix "${INTERNAL_METRIC_PREFIX:-openmetric.carbonapi}" \
    -logdir /openmetric/log/
