#!/bin/bash
set -e

function log() {
    echo "[grafana-wrapper] $@"
}

function create_grafana_conf() {
    cp /usr/share/grafana/conf/sample.ini /openmetric/grafana/conf/grafana.ini
}

function prepare_conf() {
    if test ! -e /openmetric/grafana/conf/grafana.ini; then
        log "Creating grafana.ini ..."
        create_grafana_conf
    fi

    if test ! -e /openmetric/grafana/data/grafana.db; then
        ADMIN_PASSWORD=$(cat /dev/urandom | tr -dc 'A-Z-a-z-0-9%_' | head -c${1:-20})
        echo "Running for the first time, generating random admin password: $ADMIN_PASSWORD"
        sed -i "s@;admin_password = admin@admin_password = $ADMIN_PASSWORD@g" /openmetric/grafana/conf/grafana.ini
    fi
}

prepare_conf

log "Starting grafana-server ..."
exec grafana-server \
    --homepath=/usr/share/grafana \
    --config=/etc/grafana/grafana.ini \
    cfg:default.paths.data="/openmetric/grafana/data" \
    cfg:default.paths.logs="/openmetric/grafana/log" \
    cfg:default.paths.plugins="/openmetric/grafana/plugins"
